### PR TITLE
Exemptions refactor and design

### LINKED ISSUE #257: implement design for entity page
Follow the mockups from Uri (please link to them or upload them here)

### LINKED ISSUE #283: איחוד של "משרד הבינוי" ו"משרד הבינוי והשיכון"
יש לאחד את שמות המשרדים בדיבי. 

בכל הרשומות שבהן מצויין "משרד הבינוי והשיכון" יש לשנות ל"משרד הבינוי" (השם החדש).

### LINKED ISSUE #308: exemptions with unknown volume (סכום לא ידוע(
בממשק הגרפי  יש לרשום "סכום לא ידוע" רק ברשומות שבהן סטאטוס ההחלטה הוא "טרום החלטת וועדה". 
אחרת, אם סכום = 0 או 1, ועילת הפטור היא התקשרות המשך, יש לרשום "על חשבון התקשרות קודמת".

Write "unknown volume" only in exemptions where decision = 'טרום החלטת ועדה'
Otherwise, if volume =0 or 1, and regulation like '%התקשרות המשך%' then write "על חשבון התקשרות קודמת". @Bnaya

### LINKED ISSUE #314: share link to "specific exemption view"
In the "exemptions updates page" (http://staging.open-budget-il.appspot.com/#spending///), for each exemption there should be an option to share link of the specific exemption view (i.e. the view of the supplier page, when the specific exemption is open). the share botton should be right to the supplier_id (which is on the top left side).

This will enable to share not only the supplier page but also the page with the view of the specific exemption. 

@Bnaya @uripaz9  @naamac

### LINKED ISSUE #319: add multiple selection filter of publishers and sort option to exemption update
The recent exemption page should implement a sort and a multiple selection of publishers without requesting each selection from the API.
In order for this feature to be implemented in the client side all the data from the selected dates range should be loaded to the client. The limit sent to the API request should be 10,000.

The multiple select field (סנן משרדים) should be placed to the right of the dates range field. When clicked it should open a multiple selection list of all the publishers with an option to select all which is the default. When multiple offices have been selected the field should indicate so with the text "בחירה מרובה".

The sort field (מיין לפי) should be placed to the left of the dates range field. The sort options are: total flags (עניין), volume (סכום), update date (תאריך). The default is total flags. When sorting by volume, the records without a volume should be treated as 0. @Bnaya @naamac

### LINKED ISSUE #324: add "download supplier data" button
For each supplier, in the supplier page, please implement a "download data" button. Pressing the button should download all the data in csv form. exemptions and supports should appear in 2 seperate files (one for exemptions and one for supports). The files will include all the data as in the re:dash. 
The button should be located in the lower left corner (below the supports list), and should be titled:
"הורדת נתוני ספק" .

@Bnaya @akariv @naamac @uripaz9

### PR DESCRIPTION
**Pull request by Bnaya**
Live version: http://obudget2.bnaya.net/

fixes #319
fixes #324 
fixes #314
fixes #308
fixes #283
fixes #257

### CODE REVIEW

**Comment by akariv** [comment]
Hi,

Quick review of the deployed version:
- Entity page stopped working (http://obudget2.bnaya.net/#entity/514152420/2015/main)
- Exemptions page: 
    - No way to reach to original exemption page (in mr.gov.il)
    - Download data links design should conform to the current design (see here for example: http://obudget2.bnaya.net/#budget/0780/2014/main)
    - Downloaded data should come from the server and not the client. 
     e.g.:
       http://www.obudget.org/api/exemption/entity/520027749?o=csv&limit=10000          
       http://www.obudget.org/api/supports/entity/513240903?o=csv&limit=10000

**Comment by Bnaya** [comment]
Entity page fixed
Export changed to use the server

@uripaz9  We need to think where we want to put the link to mr.gov.il page.
Maybe we should keep it in place, and the link to our page will be in a different icon? (the share icon we wanted to add)
And take a look on the export icon

**Comment by mushon** [comment]
Please make the page header scroll to a smaller version of itself so even a scrolled item always shows its title. See suggested mockup below:
group
@naamac & @uripaz9  you might want to take on that

**Comment by Bnaya** [comment]
@akariv As we are doing all the records filtering and ordering in the client, the initial request to the server is for the last 30 days, limit to 5000, batched to 5 requests.
Sometimes it can be very slow and it takes several seconds to get the data.
I'm unfamiliar with the sever code, but i assume there's any cache layer?
How often the data changes? is it possible to fill the cache when data changes, and the requests will be always be severed from it?

**Comment by akariv** [comment]
@bnaya, yes it's possible - good idea.

**Comment by Bnaya** [comment]
photo_2015-12-31_13-28-25

תמונת העיצוב האחרונה מאורי, עדיין לא צורפה לPR הזה

**Comment by uripaz9** [comment]
screen shot 2015-12-31 at 17 48 35

צרפתי סקרינשוט מעודכן

הוספתי אייקונים של הורדה
סידרתי קצת את הקולפסים
יצרתי כפתור שיתוף ולינק לאתר מנהל הרכש

כרגע שתף התקשרות מפנה לדף ספק כשההתקשרות פתוחה במקום לפתוח רשימה של אייקונים שאפשר לשתף דרכם מייל, טוויטר וכו

שינויי מצב של כותרת בגלילה - מטופל

אשמח לקבל הערות

**Comment by Bnaya** [comment]
@akariv I've pushed more changes and bug fixes
Most of the what we want is in here, other things can wait for another iteration.

The only thing i'm concerned about is the periodically long time of the initial load (in these moments its very fast)

**Comment by akariv** [comment]
@Bnaya great, I'll take a look in a few hours.
Re the load times, I'll take care of pre-heating the cache.

**Pull request merged**
