### PR TITLE
Fix build for production

### PR DESCRIPTION
**Pull request by Bnaya**
The build output wasn't complete. when you run the website from the dist/ directory after build you got broken app

There is redundent font declaration for glyphicons-halflings-regular.woff and its not getting revved,
but the app is now working from the dist/

### CODE REVIEW

**Comment by Bnaya** [comment]
@akariv  @mushon  Can you double check that the dist/ is really complete and working as expected?

**Comment by akariv** [comment]
Looks good, except this file:
styles/assets/bubble-back.svg

( @Bnaya it's not your fault - can you think of a way to handle this specific case? )

**Comment by Bnaya** [comment]
There is a reference to the svgs js files, and if we want to revv the svg we need to update the path also in the javascript files
that require to update the usemin grunt task, which breaks other things in the build. it can be fixed but needs deeper digging.
So can we skip the revving of the svg files for now and just copy them over?

**Comment by Bnaya** [comment]
@akariv After further investigation its seems there is no strait-forward way to replace revved file paths inside js file (even newer version of usemin doesn't support it of the box).
I think we should keep them unrevved for now
There are other ways to overcome this (not pointing directly to assets files from js code but via resource locator with manifest that can be updates with the actual paths)

**Comment by akariv** [comment]
Yes, unrevved for svgs is quite fine I think for now.
Let's try and find a more correct solution next time we meet.

**Pull request merged**
