### PR TITLE
343-reduce-the-need-of-webpack-alias

### PR DESCRIPTION
**Pull request by MaaikeB**
fixed webpack alias issue

### CODE REVIEW

**Comment by Bnaya** [comment]
ping @akariv

**Comment by pwalsh** [comment]
Seems like a weird way to use webpack? Why not set a single entry point and require everything there. Example:

* https://github.com/openspending/babbage.ui/blob/feature/modern/webpack.config.base.js#L4
* https://github.com/openspending/babbage.ui/blob/feature/modern/src/index.js

**Comment by Bnaya** [comment]
@pwalsh can you elaborate?
It's a requirejs codebase that was transformed to work with webpack recently, and there are some patchworks around.
The project do have single entry point, the main.coffee file
open-budget/app/scripts/main.coffee

**Comment by pwalsh** [comment]
@Bnaya hmmm. Not sure what you gain, except pain, by using both. Looking at code should be quite trivial to port to CommonJS modules, get rid of require.js, and use Webpack with a simpler config.

**Comment by Bnaya** [comment]
That extra configs are not because of the AMD modules, but the location of the node_modules & bower_components location.
webpack play very nicely with AMD as is

We are gradually working to simplify the project so we simplify our webpack config,
that PR is one of the steps.

Our next iteration would probably be ES6 (or typescript)
I would love to hear your input in #299

**Comment by pwalsh** [comment]
So on #299 I'd very strongly suggest ES6, Webpack, and then gulp for extra tasks beyond what you use Webpack for :). I'd also say get rid of Bower completely and use npm for everything - I've been doing that for around 18 months and not looking back.

Still don't get why this PR has to look like this though, and Sorry @akariv for the drive by commenting :)

**Comment by Bnaya** [comment]
@pwalsh look at #343

**Pull request merged**
