### PR TITLE
MVP of new bubble flow

### PR DESCRIPTION
**Pull request by yonatann**
CAUTION - also contains requirejs which is a JS dependancy manger.

This pull requires extensive testing before going live.
Everyone please play around with it and let me know if you encounter any unexpected behaviour

### CODE REVIEW

**Comment by yonatann** [comment]
@mushon, I tried to proportionally increase the radius of the bubbles to the left but the radius can get as big as a few thousand pixels which makes their display meaningless.

For now I animate the scale which changes every time you focus on a specific bubble. This provides some indication that something has changed. 
Its not enough i know, perhaps its worth considering blurring/fading the left side bubbles so they seem distant.

**Comment by akariv** [comment]
It's not quite there yet.

However, as this is a huge change, let's try to work on it together on Monday as I would refrain from making any more changes in master to avoid merge headaches.

**Comment by yonatann** [comment]
Of course.
It was already a big merge of the upstream into this fork.

**Comment by akariv** [comment]
I'm sure it was :frowning:

**Comment by mushon** [comment]
Let’s work on it together tomorrow. Thanks!

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On July 3, 2015 at 11:55:10 PM, Adam Kariv (notifications@github.com) wrote:

I'm sure it was

**Comment by yonatann** [comment]
@mushon,
I pushed the fine tuning we did on Monday and fixed the frozen bubbles bug.

I also added a glow on the dashed bubbles, but I need you to help me fine tune it.

**Comment by mushon** [comment]
@akariv can we pull these into a branch so we can test it before merging into master?

**Comment by akariv** [comment]
@mushon 
Done (branch = yonatann__new_main_page_vis)

**Comment by yonatann** [comment]
@akariv I've merged the upstream into my fork

**Pull request closed without merging**
